# Используем базовый образ Python
FROM python:3.11-slim

# Устанавливаем системные зависимости
RUN apt-get update && apt-get install -y libgl1-mesa-glx

# Устанавливаем зависимости Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код приложения
COPY . /app
WORKDIR /app

# Устанавливаем Flask и YOLO
RUN pip install flask ultralytics opencv-python-headless

# Запускаем приложение
CMD ["python", "app.py"]
