# Используйте официальный образ Python
FROM python:3.11-slim

# Установите необходимые зависимости для OpenCV
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Установите рабочую директорию
WORKDIR /app

# Скопируйте файлы проекта
COPY . .

# Установите зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Запустите приложение
CMD ["python", "app.py"]
